[app]
title = FindMyCar
package.name = findmycar
package.domain = com.findmycar
source.dir = .
source.include_exts = py,png,jpg,kv,atlas
version = 1.0.0
requirements = python3,kivy,kivymd,plyer,pyjnius
orientation = portrait
osx.python_version = 3
osx.kivy_version = 2.3.0
fullscreen = 0
android.api = 34
android.minapi = 21
android.ndk = r26b
android.sdk = 34
android.arch = arm64-v8a
android.permissions = ACCESS_FINE_LOCATION, ACCESS_COARSE_LOCATION, ACCESS_BACKGROUND_LOCATION, CAMERA, INTERNET
android.add_activities = org.kivy.android.PythonActivity
android.add_jars = 
android.add_src = 
android.gradle_dependencies = 
android.gradle_api_version = 34
android.wakelock = True
android.library_references = 
android.manifest_matches = 
android.add_src =
android.add_activity =
android.add_activity_meta_data =
android.add_screen =
android.add_keyboard_height =
android.add_presplash =
android.add_presplash_scale = 
android.add_presplash_bg_color = 0d1117
android.add_presplash_loading_color = 00e5ff
android.add_presplash_animation = 
android.add_presplash_bg = 
android.add_presplash_icon = assets/logo.png
android.add_presplash_icon_bg_color = 0d1117
android.add_presplash_icon_scale = 0.6
android.add_presplash_bg = 
android.add_presplash_bg_scale = 
android.add_presplash_bg_color = 
android.add_presplash_bg_scale = 
android.add_presplash_bg = 
android.add_presplash_bg_scale = 
android.add_presplash_bg_color = 
android.add_presplash_bg_scale = 
android.add_background_location = True
presplash.bg_color = 0d1117
presplash.loading_color = 00e5ff
icon = assets/icon.png
presplash.filename = assets/logo.png
presplash.scale = 0.6
presplash.bg = 
presplash.loading = 
[buildozer]
log_level = 2
warn_on_root = 1